### ISSUE TITLE
`ParseError` does not implement `std::error::Error`

### ISSUE THREAD

**Issue by elizagamedev** [pnevyk/loe#3]
This makes it difficult to interoperate loe errors with crates like snafu.

My workaround for now:

```rust
#[derive(Debug)]
pub struct LoeParseErrorWrapper(loe::ParseError);

impl Display for LoeParseErrorWrapper {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.fmt(f)
    }
}

impl std::error::Error for LoeParseErrorWrapper {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match &self.0 {
            loe::ParseError::InvalidEncoding(_) => None,
            loe::ParseError::IoError(e) => Some(e),
        }
    }
}
```

**Comment by pnevyk** [comment]
Thanks for the report. The `Error` trait should now be implement in v0.2.1. I also released v0.3.0 where I fixed naming case of some types and enum variants to follow pascal case convention, if you are interesting in upgrading to a version with breaking changes.
